# Generated by Django 4.0.5 on 2022-06-30 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('est', models.DateField()),
                ('about_the_company', models.TextField()),
                ('logo_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(default=-1)),
                ('price', models.FloatField(default=0)),
                ('color', models.CharField(max_length=100)),
                ('top_wood', models.CharField(max_length=100)),
                ('back_wood', models.CharField(max_length=100)),
                ('has_electronics', models.BooleanField(default=0)),
                ('short_description', models.TextField()),
                ('num_of_strings', models.IntegerField()),
                ('photo1_url', models.CharField(max_length=200)),
                ('photo2_url', models.CharField(max_length=200)),
                ('photo3_url', models.CharField(max_length=200)),
                ('photo4_url', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sound.brand')),
            ],
        ),
    ]
